// Generated by CoffeeScript 1.3.3
(function() {
  var EventEmitter, ForwardingStream, Pool, WebPool, async, createProcess,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  createProcess = require('./process').createProcess;

  EventEmitter = require('events').EventEmitter;

  ForwardingStream = require('./streams').ForwardingStream;

  async = require('async');

  Pool = (function(_super) {

    __extends(Pool, _super);

    function Pool(name, command, options) {
      var instance, proc, _i, _ref, _ref1,
        _this = this;
      this.name = name;
      this.command = command;
      if (options == null) {
        options = {};
      }
      this.concurrency = (_ref = options.concurrency) != null ? _ref : 1;
      this.out = new ForwardingStream;
      this.processes = [];
      for (instance = _i = 1, _ref1 = this.concurrency; 1 <= _ref1 ? _i <= _ref1 : _i >= _ref1; instance = 1 <= _ref1 ? ++_i : --_i) {
        proc = createProcess("" + this.name + "." + instance, this.command, options);
        proc.on('ready', function() {
          return proc.out.pipe(_this.out, {
            end: false
          });
        });
        this.processes.push(proc);
      }
    }

    Pool.prototype.spawn = function() {
      var process, spawned, waiting, _i, _len, _ref;
      waiting = [];
      spawned = false;
      _ref = this.processes;
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        process = _ref[_i];
        waiting.push(process);
        process.on('ready', function() {
          var index;
          index = waiting.indexOf(process);
          waiting.splice(index, 1);
          if (spawned && waiting.length === 0) {
            return this.emit('pool:ready');
          }
        });
        process.spawn();
        this.emit('process:spawn', process);
      }
      spawned = true;
      if (waiting.length === 0) {
        return this.emit('pool:ready');
      }
    };

    Pool.prototype.kill = function(callback) {
      var kill;
      kill = function(process, cb) {
        return process.kill(cb);
      };
      return async.forEach(this.processes, kill, callback);
    };

    Pool.prototype.terminate = function(callback) {
      var terminate;
      terminate = function(process, cb) {
        return process.terminate(cb);
      };
      return async.forEach(this.processes, terminate, callback);
    };

    Pool.prototype.quit = function(callback) {
      var quit;
      quit = function(process, cb) {
        return process.quit(cb);
      };
      return async.forEach(this.processes, quit, callback);
    };

    return Pool;

  })(EventEmitter);

  WebPool = (function(_super) {

    __extends(WebPool, _super);

    function WebPool() {
      return WebPool.__super__.constructor.apply(this, arguments);
    }

    return WebPool;

  })(Pool);

  exports.createPool = function() {
    var args, name;
    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (name === 'web') {
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(WebPool, [name].concat(__slice.call(args)), function(){});
    } else {
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(Pool, [name].concat(__slice.call(args)), function(){});
    }
  };

}).call(this);
