// Generated by CoffeeScript 1.3.3
(function() {
  var EventEmitter, LineBuffer, PrependingBuffer, Process, WebProcess, color, getOpenPort, net, spawn, sprintf, strftime, tryConnect, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  net = require('net');

  color = require("ansi-color").set;

  strftime = require('strftime');

  sprintf = require('sprintf').sprintf;

  EventEmitter = require('events').EventEmitter;

  spawn = require('child_process').spawn;

  _ref = require('./streams'), LineBuffer = _ref.LineBuffer, PrependingBuffer = _ref.PrependingBuffer;

  Process = (function(_super) {

    __extends(Process, _super);

    function Process(name, command, options) {
      var _ref1;
      this.name = name;
      this.command = command;
      if (options == null) {
        options = {};
      }
      this.cwd = options.cwd;
      this.pad = (_ref1 = options.pad) != null ? _ref1 : 6;
      this.color = options.color;
    }

    Process.prototype.spawn = function() {
      var env, format, key, message, value, _ref1;
      env = {};
      _ref1 = process.env;
      for (key in _ref1) {
        value = _ref1[key];
        env[key] = value;
      }
      if (this.port) {
        env['PORT'] = this.port;
      }
      env['PS'] = this.name;
      this.child = spawn('/bin/sh', ['-c', this.command], {
        env: env,
        cwd: this.cwd,
        stdio: 'pipe'
      });
      format = "%-" + this.pad + "s";
      message = "" + (strftime("%H:%M:%S")) + " " + (sprintf(format, this.name)) + " | ";
      if (this.color != null) {
        message = color(message, this.color);
      }
      this.out = new PrependingBuffer(message);
      this.child.stdout.pipe(new LineBuffer()).pipe(this.out);
      this.child.stderr.pipe(new LineBuffer()).pipe(this.out);
      return this.spawned();
    };

    Process.prototype.spawned = function() {
      return this.emit('ready');
    };

    Process.prototype.kill = function(callback) {
      if (this.child) {
        if (callback) {
          this.child.once('exit', callback);
        }
        return this.child.kill('SIGKILL');
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    Process.prototype.terminate = function(callback) {
      if (this.child) {
        if (callback) {
          this.child.once('exit', callback);
        }
        return this.child.kill('SIGTERM');
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    Process.prototype.quit = function(callback) {
      if (this.child) {
        if (callback) {
          this.child.once('exit', callback);
        }
        return this.child.kill('SIGQUIT');
      } else {
        return typeof callback === "function" ? callback() : void 0;
      }
    };

    return Process;

  })(EventEmitter);

  WebProcess = (function(_super) {

    __extends(WebProcess, _super);

    function WebProcess() {
      return WebProcess.__super__.constructor.apply(this, arguments);
    }

    WebProcess.prototype.timeout = 30000;

    WebProcess.prototype.spawn = function() {
      this.port = getOpenPort();
      return WebProcess.__super__.spawn.apply(this, arguments);
    };

    WebProcess.prototype.spawned = function() {
      var _this = this;
      return tryConnect(this.port, this.timeout, function(err) {
        if (err) {
          return _this.emit('error', err);
        } else {
          return _this.emit('ready');
        }
      });
    };

    return WebProcess;

  })(Process);

  tryConnect = function(port, timeout, callback) {
    var decay, socket, timedOut, timeoutId;
    decay = 100;
    timedOut = false;
    timeoutId = setTimeout((function() {
      return timedOut = true;
    }), timeout);
    socket = new net.Socket;
    socket.on('connect', function() {
      clearTimeout(timeoutId);
      socket.destroy();
      return callback();
    });
    socket.on('error', function(err) {
      if (timedOut) {
        clearTimeout(timeoutId);
        return callback(err);
      } else if (err.code === 'ECONNREFUSED') {
        return setTimeout(function() {
          return socket.connect(port);
        }, decay *= 2);
      } else {
        clearTimeout(timeoutId);
        return callback(err);
      }
    });
    return socket.connect(port);
  };

  getOpenPort = function() {
    var port, server;
    server = net.createServer();
    server.listen(0);
    port = server.address().port;
    server.close();
    return port;
  };

  exports.createProcess = function() {
    var args, name;
    name = arguments[0], args = 2 <= arguments.length ? __slice.call(arguments, 1) : [];
    if (name.match(/^web/)) {
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(WebProcess, [name].concat(__slice.call(args)), function(){});
    } else {
      return (function(func, args, ctor) {
        ctor.prototype = func.prototype;
        var child = new ctor, result = func.apply(child, args), t = typeof result;
        return t == "object" || t == "function" ? result || child : child;
      })(Process, [name].concat(__slice.call(args)), function(){});
    }
  };

}).call(this);
