// Generated by CoffeeScript 1.3.3
(function() {
  var Server, createFormation, dirname, parseProcfile, readFile,
    __slice = [].slice;

  readFile = require('fs').readFile;

  dirname = require('path').dirname;

  parseProcfile = require('./procfile').parseProcfile;

  createFormation = require('./formation').createFormation;

  Server = (function() {

    function Server(procfile, callback) {
      var _this = this;
      this.procfile = procfile;
      this.cwd = dirname(this.procfile);
      parseProcfile(this.procfile, function(err, details) {
        if (err) {
          return callback(err);
        }
        _this.formation = createFormation(details, {
          cwd: _this.cwd,
          concurrency: 3
        });
        _this.formation.spawn();
        return callback;
      });
    }

    return Server;

  })();

  exports.createServer = function() {
    var args;
    args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
    return (function(func, args, ctor) {
      ctor.prototype = func.prototype;
      var child = new ctor, result = func.apply(child, args), t = typeof result;
      return t == "object" || t == "function" ? result || child : child;
    })(Server, args, function(){});
  };

}).call(this);
