// Generated by CoffeeScript 1.3.3
(function() {
  var LineBuffer, PrependingBuffer, Stream, WritableStream, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; },
    __slice = [].slice;

  _ref = require('stream'), Stream = _ref.Stream, WritableStream = _ref.WritableStream;

  LineBuffer = (function(_super) {

    __extends(LineBuffer, _super);

    function LineBuffer() {
      var _this = this;
      this.readable = true;
      this._buffer = "";
      this.on('pipe', function(src) {
        src.on('data', function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.write.apply(_this, args);
        });
        return src.on('end', function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.end.apply(_this, args);
        });
      });
    }

    LineBuffer.prototype.write = function(chunk) {
      var index, line, _results;
      this._buffer += chunk;
      _results = [];
      while ((index = this._buffer.indexOf("\n")) !== -1) {
        line = this._buffer.slice(0, index) + '\n';
        this._buffer = this._buffer.slice(index + 1, this._buffer.length);
        _results.push(this.emit('data', line));
      }
      return _results;
    };

    LineBuffer.prototype.end = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (args.length > 0) {
        this.write.apply(this, args);
      }
      if (this._buffer.length > 0) {
        this.emit('data', this._buffer);
      }
      return this.emit('end');
    };

    return LineBuffer;

  })(Stream);

  PrependingBuffer = (function(_super) {

    __extends(PrependingBuffer, _super);

    function PrependingBuffer(preamble) {
      var _this = this;
      this.preamble = typeof preamble === 'function' ? preamble : function() {
        return preamble.toString();
      };
      this.on('pipe', function(src) {
        src.on('data', function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.write.apply(_this, args);
        });
        return src.on('end', function() {
          var args;
          args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
          return _this.end.apply(_this, args);
        });
      });
    }

    PrependingBuffer.prototype.write = function(chunk) {
      return this.emit('data', this.preamble() + chunk);
    };

    PrependingBuffer.prototype.end = function() {
      var args;
      args = 1 <= arguments.length ? __slice.call(arguments, 0) : [];
      if (args.length > 0) {
        this.write.apply(this, args);
      }
      return this.emit('end');
    };

    return PrependingBuffer;

  })(Stream);

  exports.LineBuffer = LineBuffer;

  exports.PrependingBuffer = PrependingBuffer;

}).call(this);
